created latest notice section
ms-club-sliit/fcmu pull request #22
Opened 2023-03-14 03:42 UTC by ChathukaViduranga

2023-03-14 14:44 UTC, senuravihanjayadeva requested changes
Please maintain formatting using prettier.
Change the target branch to feature/dev

2023-03-14 14:44 UTC, senuravihanjayadeva commented on src/components/client/landing/latestNotice/LatestNotice.jsx
> +import notice1 from './../../../../assets/images/notice/notice1.jpeg'
Dont use jpeg. Please covert images to webp. Do the same thing for others

2023-03-14 14:44 UTC, senuravihanjayadeva commented on src/components/client/landing/latestNotice/LatestNotice.jsx
> +            {images.map((image, index) => (
First check images exists or not

2023-03-14 14:44 UTC, senuravihanjayadeva commented on src/components/client/landing/latestNotice/LatestNotice.jsx
> +          {images.map((_, index) => (
check images exists or not

2023-03-14 15:21 UTC, ChathukaViduranga commented on src/components/client/landing/latestNotice/LatestNotice.jsx
> +          {images.map((_, index) => (
ok. I'll do it

2023-03-15 09:07 UTC, uihalagedara commented
upload a screenshot of the implemented component as well

2023-03-15 09:28 UTC, ChathukaViduranga commented
<img width="1357" alt="Screenshot 2566-03-15 at 14 56 03" src="https://user-images.githubusercontent.com/77539211/225266500-828c476c-be72-4b3a-94cd-afc752538029.png">

2023-03-15 09:34 UTC, ChathukaViduranga commented
![WhatsApp Image 2023-03-15 at 15 03 38](https://user-images.githubusercontent.com/77539211/225268189-c0a2d1e5-4a11-40fe-ba4e-bdb702b995f6.jpeg)

2023-03-15 10:22 UTC, merged