Events Page Hero Section + bug fixes
ms-club-sliit/fcmu pull request #31
Opened 2023-03-20 10:39 UTC by Navojith

2023-03-20 15:45 UTC, senuravihanjayadeva requested changes

2023-03-20 15:45 UTC, senuravihanjayadeva commented on src/components/client/eventsPage/HeroSection/index.jsx
> +              <img id="events-hero-img" src={imgSrc} />
add alt text

2023-03-20 15:45 UTC, senuravihanjayadeva commented on src/routes/index.jsx
>          <Route path="/" element={<LandingPage />} />
put this at the end

2023-03-20 15:45 UTC, senuravihanjayadeva commented on src/components/client/eventsPage/HeroSection/index.jsx
> +              <img id="events-hero-img" src={imgSrc} />
There are several reasons why adding alt text to the "img" tag is important:

Accessibility: Adding alt text to an image is essential for making your content more accessible to people with visual impairments or those who rely on screen readers. When an image has an alt text, the screen reader will read out the description to the user, providing them with a better understanding of what the image contains.

SEO: Search engines use alt text to understand what the image is about, which can improve the visibility of your website in search engine results pages (SERPs). Without alt text, search engines may have a hard time understanding what your content is about and may not index it properly.

Placeholder: If an image fails to load, the alt text will be displayed instead, providing context to the user.

2023-03-21 04:36 UTC, Navojith commented on src/components/client/eventsPage/HeroSection/index.jsx
> +              <img id="events-hero-img" src={imgSrc} />
oh I didnt know that. thank you. I will add that too

2023-03-21 07:39 UTC, uihalagedara commented
LGTM

2023-03-21 07:39 UTC, uihalagedara approved these changes

2023-03-21 07:40 UTC, merged