Issue #26 About us "Board of official" Section Completed
ms-club-sliit/fcmu pull request #37
Opened 2023-04-10 18:46 UTC by shafdo

Issue #26 About us "Board of official" Section Completed

Screenshot
![image](https://user-images.githubusercontent.com/30050702/230970722-f0466200-fa4a-4ee5-96d0-0e71ff86a781.png)

TODO: The original board member data must be added to the `boardMembers.json` file.

2023-04-10 19:51 UTC, shafdo commented
Issue #25 About us "Who We Are" Section Completed

![image](https://user-images.githubusercontent.com/30050702/230985067-885523d1-6911-47cc-9d29-314c73857bf7.png)

2023-04-11 02:56 UTC, MadhushaPrasad commented on src/components/client/about/boardSection/index.jsx
> +/* eslint-disable no-restricted-syntax */
remove this eslint-disable options, please be kind to use eslint rules

2023-04-11 02:56 UTC, MadhushaPrasad commented on src/components/client/about/boardSection/index.jsx
> +import instagram from '../../../../assets/images/AboutPage/instagram.svg'
use fontawesome for this social media icons

2023-04-11 02:57 UTC, MadhushaPrasad commented on src/components/client/about/boardSection/index.jsx
> +              <option value="2022">2022</option>
set default value as 2022 in here

2023-04-11 02:58 UTC, MadhushaPrasad commented on src/components/client/about/boardSection/index.jsx
> +            <select name="" id="board-year" onChange={ArrangeBoard}>
remove border in the select element, style it like the Figma design

2023-04-11 03:00 UTC, MadhushaPrasad commented on src/components/client/about/boardSection/index.jsx
> +const SocialLinkedin = (props) => {
remove these functions and replace those with fontawesome icons

2023-04-11 03:00 UTC, MadhushaPrasad commented on src/components/client/about/whoWeAreSection/index.jsx
> +/* eslint-disable react/jsx-no-useless-fragment */
remove eslint disable options

2023-04-11 03:02 UTC, MadhushaPrasad commented on src/components/client/common/header/index.jsx
> +                <a href="/about" className="nav-link">
replace anchor tag with Link use react-router-dom for navigations

2023-04-11 03:02 UTC, MadhushaPrasad commented on src/pages/AboutPage.jsx
> +/* eslint-disable react/jsx-no-useless-fragment */
remove these also

2023-04-11 03:03 UTC, MadhushaPrasad requested changes
- [ ] use social media icons by fontawesome, dont use as svg icons
- [ ] fix left side padding as in our figma file
![image](https://user-images.githubusercontent.com/50085447/231042915-1a81f652-a6d7-4c8e-aa55-c96ae20b7dbb.png)

- [ ] remove border in 'select year' dropdown element -> make it as figma file -> you can get that styles from figma inspect section
- [ ] bind board of official data to all of cards remove this images.
![image](https://user-images.githubusercontent.com/50085447/231043749-f2dd74d5-3c28-4c30-9a0f-24435b4a675f.png)

- [ ] remove eslint-disable and use our eslint rules

2023-04-15 05:21 UTC, closed without merging